stages:
  - test
  - build
  - deploy

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  stage: test
  script:
    - bundle exec rake spec

rubocop:
  stage: test
  script:
    - bundle exec rake rubocop

build:
  stage: build
  script:
    - bundle exec rake build
  only:
    - tags

deploy:
  stage: deploy
  environment:
    - name: production
    - url: http://rubygems.athenahealth.com
  script:
    - bundle exec rake release
  only:
    - tags